title: AmadeusGPT
author: MLAI
logo: docs/logo.png
only_build_toc_files: true

sphinx:
  config:
    autodoc_mock_imports: list #["wx"]
  extra_extensions:
    - numpydoc

execute:
  execute_notebooks: "off"

html:
  extra_navbar: ""
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.</div>

repository:
  url: https://github.com/AdaptiveMotorControlLab/AmadeusGPT
  path_to_book: main
  branch: main

launch_buttons:
  colab_url: "https://colab.research.google.com/github.com/AdaptiveMotorControlLab/AmadeusGPT/examples/yourdemo.ipynb"
