keypoint_info:
llm_info:
  keep_last_n_messages: 2  
object_info:
  load_objects_from_disk: false
video_info:
  scene_frame_number: 100
  video_file_path: 
data_info:
  data_folder: 'examples/Custom'
  video_suffix: '.mp4'
  result_folder: 'results'