keypoint_info:
  keypoint_file_path:
llm_info:
  keep_last_n_messages: 2  
object_info:
  load_objects_from_disk: false
video_info:
  scene_frame_number: 100
  video_file_path: 
result_info:
  result_folder: "./results"