keypoint_info:
  body_orientation_keypoints:
    neck: "nose"
    tail_base: "tail_base"
    animal_center: "neck"
  head_orientation_keypoints:
    nose: "nose"
    neck: "neck"  
object_info:
  load_objects_from_disk: false
llm_info:
  keep_last_n_messages: 2
video_info:
  scene_frame_number: 100
data_info:
  data_folder: 'examples/EPM'
  video_suffix: '.mp4'
  result_folder: 'results'
