keypoint_info:
  keypoint_file_path: "examples/MABe/mabe_EGS8X2MN4SSUGFWAV976.h5"
  model_checkpoint: ""
  model_name: ""
  body_orientation_keypoints:
    neck: "nose"
    tail_base: "tail base"
    animal_center: "neck"
  head_orientation_keypoints:
    nose: "nose"
    neck: "neck"  
object_info:
  load_objects_from_disk: false
sam_info:
  ckpt_path: "path/to/ckpt"
  model_type: "sam"
video_info:
  scene_frame_number: 100
  video_file_path: "examples/MABe/EGS8X2MN4SSUGFWAV976.mp4"