keypoint_info:
  keypoint_file_path: "examples/MausHaus/maushaus_trimmedDLC_snapshot-1000.h5"
  model_checkpoint: ""
  model_name: ""
  body_orientation_keypoints:
    neck: "nose"
    tail_base: "tail_base"
    animal_center: "neck"
  head_orientation_keypoints:
    nose: "nose"
    neck: "neck"  
llm_info:
  keep_last_n_messages: 2
object_info:
  load_objects_from_disk: false
video_info:
  scene_frame_number: 100
  video_file_path: "examples/MausHaus/maushaus_trimmedDLC_snapshot-1000_labeled_x264.mp4"